### ISSUE TITLE
ArgumentError: negative argument with new swf

### ISSUE THREAD

**Issue by hartator** [andersonbrandon/ruby-imagespec#3]
Hey,

I've found an issue with new swf :

```
ArgumentError: negative argument
from /Users/Bob/apps/ugs/lib/imagespec/parser/swf.rb:54:in `*'
```

Thanks a lot for this library anyway!

**Comment by andersonbrandon** [comment]
Thanks for the heads-up.  Can you provide any additional insight other than the error?  What type of SWF were you using? Which version of Flash was it exported from, etc.?

**Comment by hartator** [comment]
Sorry about the lack on informations, it's a flash game, to reproduce :
`a = open 'http://uploads.ungrounded.net/591000/591169_Peng_bomb_BESTVERSIONMUSIC.swf'`
`ImageSpec.new a.path`

**Comment by andersonbrandon** [comment]
Thanks for the additional information.  Looks like the line of code responsible for determining the nbits used in the SWF was using a lower-case 'c' and thus returning a signed integer, as opposed to the unsigned integer specified in the SWF spec.

I've pushed a change that should resolve the problem and reports your SWF dimensions to be 900x600.

woo!

**Comment by hartator** [comment]
Great, thank you! I've been trying other libraries on the internet in ruby and others, and, according to my tests, the script you have wrote is one of the best on the internet for finding swf size, you beat even http://www.swftools.org/,  great work! :)

**Comment by cqc1008** [comment]
Thanks for your share!
I install newest version(0.3.1) with bundler, this issue still exists.
So I need to write ":git => 'https://github.com/andersonbrandon/ruby-imagespec.git'" to Gemfile.
Can you share an new version? Thanks!
